server:
  port: 9999



spring:
#  cloud:
#    inetutils:
#      preferred-networks: 8.134.18.54
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_qft?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: lf18289339306
  jackson:  #JSON日期格式化
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
  mvc:  #日期格式化
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  ################################# Redis相关配置 #################################
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    #自定义属性
    expire: 60000



mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #type-aliases-package: com.qft.web.**.entity
#  configuration:
#    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0




logging:
  config: classpath:logback.xml


#jwt配置
#密钥
jwt:
  secret: com.qft
  expiration: 1800000


secure:
  ignored:
    urls: #安全路径白名单
#      - /**
      - /api/user/login
      - /api/user/register
      - /api/msm/send
      - /api/msm/verification
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /v2/**
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/**
      - /druid/**
      - /static/qrcode/**




short:
  message:
    access-key-id: LTAI4GJ6aa5zmUTuAMmteoss
    secret: 53eD9YFsPyTEHxBLxgpyB1mDY4ChHD
    template-code: SMS_199222499
    sign-name: 我的全法通平台